/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A Creature
 */
export interface Creature {
  id: string;
  name?: string;
  alive?: boolean;
  hp?: number;
  category?: string;
  initiative?: number;
}
