[project]
name = "python-csv-cleanup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jsonschema>=4.23.0",
    "pandas>=2.2.3",
    "python-jsonschema-objects>=0.5.7",
]
